### ISSUE TITLE
发布报错

### ISSUE THREAD

**Issue by goerzh** [Qihoo360/wayne#228]
Deployment 发布报错
```
Deployment.apps "zage-test" is invalid: spec.template.spec.containers[0].env[0].name: Required value 
```
yaml 文件：
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zager-test
  labels:
    wayne-app: zager
    wayne-ns: test
    app: zager-test
spec:
  selector:
    matchLabels:
      app: zager-test
  template:
    metadata:
      labels:
        wayne-app: zager
        wayne-ns: test
        app: zager-test
    spec:
      containers:
        - resources:
            limits:
              memory: 1Gi
              cpu: '1'
            requests:
              memory: 1Gi
              cpu: '0.5'
          name: zager-test
          image: ccr.ccs.tencentyun.com/kuainiu/zager
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 1
```
