### ISSUE TITLE
 Invalid param KubeDeployment ! 

### ISSUE THREAD

**Issue by haoprogrammer** [Qihoo360/wayne#304]
Deployment 发布报错
` Invalid param KubeDeployment ! `

yaml文件为：
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: saas-nginx
  labels:
    wayne-app: saas
    wayne-ns: saasdemp
    app: saas-nginx
spec:
  selector:
    matchLabels:
      app: saas-nginx
  template:
    metadata:
      labels:
        wayne-app: saas
        wayne-ns: saasdemp
        app: saas-nginx
    spec:
      containers:
        - resources:
            limits:
              memory: 0.2Gi
              cpu: '0.2'
            requests:
              memory: 0.2Gi
              cpu: '0.1'
          name: saas-nginx
          image: 'nginx:latest'
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 1
```

问题描述：
用wayne发布出现 Invalid param KubeDeployment ! 不能发布。
用kubectl命令行执行yaml文件没有问题，能发布成功。

环境：
wayne：v1.4.1
