### ISSUE TITLE
计划任务提交后报错，并无法再点开高级配置

### ISSUE THREAD

**Issue by GinoDevOps** [Qihoo360/wayne#38]
#点chuang ji创建计划任务模版
![image](https://user-images.githubusercontent.com/22426397/48823157-bdcee700-ed9a-11e8-992c-9eeefdc3b6a0.png)
#使用官方提供的yaml文件（在系统中已经成功apply并执行）
![image](https://user-images.githubusercontent.com/22426397/48823208-e9ea6800-ed9a-11e8-9dfe-af067c792742.png)
#手动补全内容，然后点击提交
![image](https://user-images.githubusercontent.com/22426397/48823243-0686a000-ed9b-11e8-8c54-7d5977bc2240.png)
#提交后，提交按钮变成灰色，f12发现报错，并且点高级配置没有反应，需要刷新页面
![image](https://user-images.githubusercontent.com/22426397/48823135-ae4f9e00-ed9a-11e8-8fbd-f3d70bf97b7b.png)

**Comment by GinoDevOps** [comment]
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure

**Comment by GinoDevOps** [comment]
> application/job/cronjob.yaml  
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure

**Comment by GinoDevOps** [comment]
附官方yaml地址：
https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/

**Comment by GinoDevOps** [comment]
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```
