### ISSUE TITLE
 Get https://192.168.6.162/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions: x509: cannot validate certificate for 192.168.6.162 because it doesn't contain any IP SANs 

### ISSUE THREAD

**Issue by iedwin** [Qihoo360/wayne#412]
我按照文档添加了cluster，但是在node等面板是空的。点击namespace和CRD时候会报错：
Get https://192.168.6.162/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions: x509: cannot validate certificate for 192.168.6.162 because it doesn't contain any IP SANs .
添加cluster时，Master我试过master的ip和VIP都不行，192.168.6.162,192.168.6.10(VIP)

Kubeconfig:
```yaml
kind: Config
apiVersion: v1
preferences: {}
clusters:
  - name: k8s-dev
    cluster:
      server: 'https://192.168.6.162'
      certificate-authority-data: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1ETXlPVEV4TXprd01sb1hEVEk1TURNeU5qRXhNemt3TWxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS0d0ClVzVllJTmIrbzVJaFNLVnFiN0xUeUhmY2dTVldQVzVTY2wrRGx0N1RtSmVGQWQ1ckpuVU5PWWFrU2U4OGYrQjUKQ0ZoZmdwbVRxZkJRZ293MmlHeGJOYTZwdzdRV2s5Zjg2MmM4bW5sSkhlZVV4VG4rQ0JSZFhyanY1dmNtcEgvdQpyQlphS1pFckRZSGRtc094b05KNTA1RWZKRk96TWxuamRJTDMxUFZRM2Z0dndLQ0JCZURyaFpPQks2Uys5dGI1Cm0xemx4cWJ6NkloZzNPUEJrTy9maVFGbk44Y1JSZiswR3F3aHluRWVUcXVtbzVrWkJGTWtLejA4a0RwUUM3UXMKalBaZmZOdXdLOXIvbDVpY1Jtd0FzRXR1RFB0VVhKVmkxWmgxZ3RrRTBjbjdlbEFQSVZLU3I1UjhLa0QyV0NPTwphT3RMeHdEekN3bnYrVE8vRGxjQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFHbDg3bDlwY3d6cnhoN3dnRmthN2crbDBoRHkKTElQcVBuOTlIQ2U1eDM3WmtBYmNPMmgxWHNsR1h4LzJ6TEdZWmlOdWRtWTVDWDEwdmduNk5CTnVFWlNuTi9zKwo4NnFNanFiemdWYmt6RkFsTm8vNUpFMjVpVm1Vd0Z6a2lNTXNJZ29OQW5JRXNyVXVLOWhYdUs1aVUwSi9MVWZSCm1GZERUckw4ZG5PRHpxYkFuZXd6TEl6VGhNMndFR3BDaWhadHBIS1A2WFRiT09IZWczaDRtSXBhb0psVEloM3UKZDdYTWordis4bTNWblhIbGJ4S2ttZjFJVW1FZERCZHZCK01kYjQrYlFwTW1kOWhWaFpvT0tEUXY0UWd3ZjJwSwp1clZrMDI2akx5UlZ3QUVhSmh6RUlDMW1YTlFBMHRmSUdHNWI1NlZPM2JlbENYU3NxQTZYdEl5QWxUYz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
users:
  - name: admin
    user:
      client-certificate-data: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4akNDQWRxZ0F3SUJBZ0lJQi9IOC91RTliRTR3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB4T1RBek1qa3hNVE01TURKYUZ3MHlNREF6TWpneE1UTTVNRFZhTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXZtaDZ6dUtDVVBiTlFPVnYKam40ZmIxNlJwUTliZGY0eU8wbUZQTFJoa0Rna1YzNTlDS1J3OXluWE5UQmgwRFVtVE5NMkpZSEc2L0tPcnpLdwpyb1l5VnZMYWlVeXdCOS9Gb0o2cUh2M1ZXOG51ZzQwK0FFS1dNVWgrNUtlc3pmS0NQUzNweXFhU3Q1cTNWVklkCndTTUYvWVRnQmRVYUtQRVBpYk5nSHF3T2JpL1J1YXBNZlVwOEtCVENQcXNUcjQ5ZXhVZnNXdnNPdzFTK0NhaTkKQ1FnTzViTlE3WXZUZmtnWnJTWGU0OW9Hbkc0dWFGeUYxbDFWZ2cxY3hEd00yV1RhdUhtZHJOOHNpRUErSG1iZgpsMU9IZHZRR1lCTmtnb3gwTWhrNlVpVmVJVUQyY0pwd1dtSUw3Uk5ScXlUYmFCTjBzdktpMWhqTXNzR0luTlNOCmpsYTRwUUlEQVFBQm95Y3dKVEFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFDYTJGdXppY0NRRlAraXM5TmRDUklSbFMzMG45L3JBWW9vVgpmSGZ6dVZLc0hDRDc2OXRLZjFHRVZUYnY4cGxtWjY0YXRBNXBXeFBETXZrSzkybTNMdjErUjFJZEpCbkZuYjFSCnJaREVZUFlCM0JXanNBRWZoUFZLQmZGNXpnZU80NTBXUlNZclBjY1VIM0V4RzU0UnlvRnlyaFZzdEpLdERXcVkKM2xDNWJKUzFmZEV1Sm01U25ZTTBNMlJhZGsvMWhmV0taN0IzNk9ES3RqZkpzNHY3NVFXV0FGNkhJTTk2TEZrZQpUTU0wQ1hzWlltK1ZnVmxwdS9MRjFpQVdNaUZaMko3Qnk3NlNFaXkyalpHbzA4STc0UEoyaytjSnpUVkNzdFZxCkI3aG5tU2dxMWRKcjhJSGRYTWV4RjJQWTRMNEdXSHNmeC9SWEt3VUc1Um5YSFVSQkhmWT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      client-key-data: >-
        LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBdm1oNnp1S0NVUGJOUU9WdmpuNGZiMTZScFE5YmRmNHlPMG1GUExSaGtEZ2tWMzU5CkNLUnc5eW5YTlRCaDBEVW1UTk0ySllIRzYvS09yekt3cm9ZeVZ2TGFpVXl3QjkvRm9KNnFIdjNWVzhudWc0MCsKQUVLV01VaCs1S2VzemZLQ1BTM3B5cWFTdDVxM1ZWSWR3U01GL1lUZ0JkVWFLUEVQaWJOZ0hxd09iaS9SdWFwTQpmVXA4S0JUQ1Bxc1RyNDlleFVmc1d2c093MVMrQ2FpOUNRZ081Yk5RN1l2VGZrZ1pyU1hlNDlvR25HNHVhRnlGCjFsMVZnZzFjeER3TTJXVGF1SG1kck44c2lFQStIbWJmbDFPSGR2UUdZQk5rZ294ME1oazZVaVZlSVVEMmNKcHcKV21JTDdSTlJxeVRiYUJOMHN2S2kxaGpNc3NHSW5OU05qbGE0cFFJREFRQUJBb0lCQUNJMTVYTE1jYnVZVEZLUApwcGFFaEtOZTYyNHJyelFwQXQ5eUd6Vkg5NHVRK3I2WnBGOXNKRHZVVWExbHp2MDR2M1BvTXY5VUxPaHh3VDhyCkxXRitEUWRnUlBHTVRNaHRaVFd4ckVFN1BCMXN6NlRsT0xHVlJTVC9zSVRtdDM2ZFJ0YzFLNTlVaEdIbXMyL3AKL0J5YWJWWWFqS0dmb3o2ZDZUdkZkY3lzL3o2K215MHM5QWVyTDJOcThISVp1TkJjVGkvZXZFL0ozZWF1d2RpUwpsbjM2ZThXRHpaL2ZUMVVmTFFkdTFuc2dsVUQ5cE9IV3c0NkxKbStPVjBhY2pHL3hSL29lWmc4Mlh0QWpMZ2oyCnI1dVgzd3pEakJENUZqVTZ4TDhYUXNPRUJlWHFJM3pqK0R5bXk4R1ZoQzFna2VFU1dGT2lNMDJuYzVVa0F5MCsKczFGdTQrRUNnWUVBekQ2ZHVTNXZpVjI4Ky9tQ0ZFVkVUeXRsb21mZG8zQy9hOEE4cDAxaGo4ZFZhWTFRZzVYbQpyZlU5UnJXMHhqREtCR2NTeTdVNHZpd2FBbXIyK2huNnplOW9jOTdCQk9kbDE4a2dUU3hSUDROV2h5bjlZNkdLCkhidktnb251SXBpNWIvN0ZKSnQ0NlREZW5rOHEyb2F6R0lkUFAyMXhaajhtdG96MUlUelRVZTBDZ1lFQTdxaEsKRGU5emdPdDRFQlIwNjBnQlRidW1QSUNaNzhHMWR3QUpkMmNreTVwNU9xd3lNcjVqUG1XZk11UEtQRklaQzl5Tgpya1loZGYzUlNka3RBVUhkd2RYb1pTVU05UWFxa05yM2pZVXN0SmxtSUZnVjVBc2t4cVlNN3RBNGw5NWNxanJMCi9PdlRxeUU2OGdwMEVzMkFFa3VLNHpvbndQZlhtZmIxMDJsRmlwa0NnWUFqRFEvbVNzakxhekhXa0ZBNWlGV2IKdkpmWmtqZWdKK1pCNktEQUdYQ0h5eTZtU2FFcW85d051SXVHaWdKM0RNSnVsUDNOeGREeUdnRndyc2lwelRHVQppK1NDRmhWTDhTWXlMUXNGRTNqeURHa2FFeU93S0hYYWVuTGJpaTQ2ODdqSE5wTEFvSW5VZ3hXQlY1YkVIOSsyCmN1b3Z1V2wvb1pEVVBVYUlLTGNmVlFLQmdHakhZQVB3UGhDNjBMS1dtS0ozc1lMVVFPN05NMGh0RG1PWms0NWwKcldUcWhCRDdhdXFXWmZJT0lhL3hER2doVHpmQzlEMHdNeDZmZWhSbkVmZzhWOFR6U2gybC82TlA4dkM0QWZtVApINGFHMXF5YW43bklIclJNVU45RWNhUlRqdkY1OFBjdy9uUmltWU9NalZ0Mzk2T1FvUUNVRnNJRXpoYWRzMTNICkdTMzVBb0dBZTdXME90YU5BR245N3RpdkEyK0cvZTdyZ3RpY1NlMFd3aWg2Nlc4Z3RRL3Fkc2UyRnQ2c1NVaFcKektHVk1rWWlUZ0lzR01DUk5tTkkyYVFQTGtwZGxNNkhlOXpXRXRmNGNLSkg5TXUycU9CUHJPWnB4dXhRMUQzaQpXZHpzbUlLelBSZEk2dXhtRTN1Sm1iYXMyZmRYR3c0Y0ZzaFV3dFR1dnVEaFIxdUxtb289Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
contexts:
  - name: k8s-dev-context
    context:
      cluster: k8s-dev
      user: admin
      namespace: default
current-context: k8s-dev-context
```
3个base64我是在master上得到的：
```sh
grep 'client-certificate-data' $HOME/.kube/config | awk '{print $2}'
grep 'certificate-authority-data' $HOME/.kube/config | awk '{print $2}'
grep 'client-key-data' $HOME/.kube/config | awk '{print $2}'
```
请问你们具体是怎么添加的？
