### ISSUE TITLE
openapi for cicd

### ISSUE THREAD

**Issue by luolizhi** [Qihoo360/wayne#436]
**Describe the bug**
wayne 1.7.1
前后端分离后，在集成cicd更新状态时会出现无法更新成功，请求前端地址http://front-path:port/openapi/v1/gateway/action/upgrade_deployment?^^^^
会直接跳转到首页，导致无法更新成功。

**To Reproduce**
使用cicd集成openapi后，无法更新新的deploy状态。
可以本地postman请求openapi的url，可以复现。

目前的解决方案是使用后端暴露出来的接口替换前端的接口。

可能的方案在前端nginx配置中增加pass_proxy.

**Comment by gaulzhw** [comment]
openapi是后端提供的api接口服务，为什么要从前端路由地址访问？
可以将前后端的路由配置一个host，通过ingress访问，根据url前缀转发前端服务或者后端服务。

后期将后端服务api化是一个计划，统一api接口，目前可以参考如下ingress配置：

```yaml
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: default-ingress
  namespace: default
spec:
  tls:
    - hosts:
        - www.qihoo.cloud
  rules:
    - host: www.qihoo.cloud
      http:
        paths:
          - path: /login
            backend:
              serviceName: infra-wayne
              servicePort: 8080
          - path: /logout
            backend:
              serviceName: infra-wayne
              servicePort: 8080
          - path: /currentuser
            backend:
              serviceName: infra-wayne
              servicePort: 8080
          - path: /api
            backend:
              serviceName: infra-wayne
              servicePort: 8080
          - path: /openapi
            backend:
              serviceName: infra-wayne
              servicePort: 8080
          - path: /ws
            backend:
              serviceName: infra-wayne
              servicePort: 8080
          - path: /healthz
            backend:
              serviceName: infra-wayne
              servicePort: 8080
          - path: /session
            backend:
              serviceName: infra-wayne
              servicePort: 8080

          - path: /
            backend:
              serviceName: infra-wayne
              servicePort: 4200
```
