### ISSUE TITLE
socketio 可以建立连接，但是发送消息不通。

### ISSUE THREAD

**Issue by q357240635** [Qihoo360/wayne#461]
配置如下：
```yaml
metadata:
  annotations:
    traefik.backend.loadbalancer.stickiness: 'true'
    traefik.backend.loadbalancer.stickiness.cookieName: socket
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_redirect off;
      proxy_buffering off;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host  $http_host;
      proxy_set_header X-Nginx-Proxy true;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
spec:
  selector:
    app: xxx
  ports:
    - protocol: TCP
      targetPort: 9092
      port: 80
      name: xxx
  type: ClusterIP
  sessionAffinity: None
```

ingress  配置如下
traefik.backend.loadbalancer.stickiness：' 
true'traefik.backend.loadbalancer.stickiness.cookieName：socket
不起作用
