### ISSUE TITLE
审计功能如何开启？

### ISSUE THREAD

**Issue by wefanWes** [Qihoo360/wayne#518]
介绍说需要安装rabbitmq来开启审计功能，但当前的docker-compose和kubernetes版本都没有了rabbit的配置，wiki里的用户安装步骤没有写明。之前有单独的rabbitmq的配置，如下方所示，但是安装上后wayne的审计功能并未有数据，查看mysql里的audit_log表也没有数据，请问在当前的build下如何开启审计功能？

RabbitMQ：
`
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-wayne
  namespace: default
  labels:
    app: rabbitmq-wayne
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-wayne
  template:
    metadata:
      labels:
        app: rabbitmq-wayne
    spec:
      containers:
      - name: rabbitmq
        image: 'rabbitmq:3.7.8-management'
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: '1'
            memory: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq-wayne
  name: rabbitmq-wayne
  namespace: default
spec:
  ports:
  - port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    app: rabbitmq-wayne
````
